remote: origin
target-branch: main
chart-dirs:
  - bitdeps/
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
excluded-charts: []
debug: true
check-version-increment: true
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
