## @section Raw App chart parameters
##
## The raw chart serves as a versatile tool for generating raw resources
## and templates. Its functionality extends beyond mere resource
## generation - it also offers a convenient interface for conditional rendering,
## allowing the chart to render multiple resources based on specific conditions.
##
## @param chartName Defines the chart/application (helm.sh/chart and app.kubernetes.io/name)
##
chartName: raw
## @param nameOverride String to partially override common.names.name (overrides app.kubernetes.io/name)
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param namespaceOverride String to fully override common.names.namespace
##
namespaceOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}


## @section Resources and features
##
## @param enableFeatures Enables/disables features default (defaultFeatures).
##
enableFeatures: true
## @param defaultFeatures Defines available features, sets the default state (enabled/disabled)
## e.g:
## defaultFeatures:
##   cadvisor: true
##   kube-state-metrics: true
##   kubernetes-nodes: true
defaultFeatures: {}
## @param rawList List of resources to render (value is rendered using tpl if type=template)
##
## e.g:
## myVariable: hello
## resourses:
## - condition: hello.enabled
##   name: somename
##   type: template
##   value:
##     apiVersion: v1
##     kind: ConfigMap
##     data:
##       foo: |-
##         {{ .Values.myVariable }}
##
rawList: []
