## @section Raw App chart parameters
##
## The raw chart serves as a versatile tool for generating raw resources
## and templates. Its functionality extends beyond mere resource
## generation - it also offers a convenient interface for conditional rendering,
## allowing the chart to render multiple resources based on specific conditions.
##
## @param chartName Defines the chart/application (helm.sh/chart and app.kubernetes.io/name)
##
chartName: raw
## @param nameOverride String to partially override common.names.name (overrides app.kubernetes.io/name)
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param namespaceOverride String to fully override common.names.namespace
##
namespaceOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}


## @section Conditional rendring parameters
##
## @param features List specifying available features (with can by enabled or disabled)
## e.g:
## features:
##   - istio
##   - kube-state-metrics
features: []
##
## @param enable List to selectively enable features - enable mode (all features are disabled by default)
## In the bellow example istio.enabled will be set to true, enablers is ignored:
## e.g:
## enable:
##   - istio
enable: []
##
## @param disable List to selectively disable features - disable mode (all feautures are on)
##
## e.g:
## disable:
##   - kube-state-metrics
disable: []
## @param resources List of resources to render (inner templates are not processed)
##
resources: []
## @param templates List of templates (same as resources, but their inner content is rendered)
##
## e.g:
## myVariable: hello
## templates:
##   - name: foo
##     value: |
##       apiVersion: v1
##       kind: ConfigMap
##       data:
##         foo: |-
##           {{ .Values.myVariable }}
templates: []
