{{/* vim: set filetype=helm: */}}
{{- define "app.resources.secret" -}}
{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-{{ ._include.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "app.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
{{- if ._include.value.data }}
data:
  {{- toYaml ._include.value.data | nindent 2 }}
{{- end }}
{{- if ._include.value.stringData }}
stringData:
  {{- $dict := dict -}}
  {{- range $key, $value := ._include.value.stringData -}}
    {{/* Render value first, since it's possible to pass a complex type (i.e map) */}}
    {{- $_ := set $dict $key (include "common.tplvalues.render" (dict "value" $value "context" $)) -}}
  {{- end -}}
  {{- $dict | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end -}}

{{- define "app.resources.secrets" -}}
  {{- range $name, $value := .Values.secrets | default dict }}
    {{- include "app.resources.include" (dict "_include" (dict "resource" "secret" "name" $name "value" $value) | mergeOverwrite $) }}
  {{- end }}
{{- end -}}

{{/* Includes this resource */}}
{{- include "app.template" . -}}