name: Lint and Test Charts
on: pull_request

env:
  charts_dir: bitdeps/

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: docker://quintush/helm-unittest:3.11.2-0.3.0
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          fetch-depth: 0
      - 
        name: Install system packages
        run: .github/scripts/runt.sh --os-install bash git
      - 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Run Unit Test
        shell: bash
        run: . .github/scripts/helpers.sh; run_unittest

  lint-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2
      -
        uses: helm/chart-testing-action@v2.6.0
      -
        name: Config chart-testing
        run: cp .github/ct.yaml $CT_CONFIG_DIR
      -
        name: Lint chart-testing
        run: ct lint
      -
        name: Exclude library charts
        id: charts
        run: . .github/scripts/helpers.sh; set_testing_output
      -
        name: Create Kubernetes Cluster (kind)
        uses: helm/kind-action@v1.5.0
        if: steps.charts.outputs.testing == 'true'
      -
        name: Test Charts
        run: ct install ${{ steps.charts.outputs.excluded-charts }}
        if: steps.charts.outputs.testing == 'true'
